export { default as Controls } from './Controls.vue'
export { default as Cover } from './Cover.vue'
export { default as Info } from './Info.vue'
export { default as Lyrics } from './Lyrics.vue'
export { default as Operations } from './Operations.vue'
