/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IFluentDismiss32Regular: typeof import('~icons/fluent/dismiss32-regular')['default']
    ISolarChatDotsLineDuotone: typeof import('~icons/solar/chat-dots-line-duotone')['default']
    ISolarFileRemoveBoldDuotone: typeof import('~icons/solar/file-remove-bold-duotone')['default']
    ISolarGalleryBoldDuotone: typeof import('~icons/solar/gallery-bold-duotone')['default']
    ISolarHamburgerMenuLineDuotone: typeof import('~icons/solar/hamburger-menu-line-duotone')['default']
    ISolarHeartBold: typeof import('~icons/solar/heart-bold')['default']
    ISolarHeartBoldDuotone: typeof import('~icons/solar/heart-bold-duotone')['default']
    ISolarHeartBrokenLineDuotone: typeof import('~icons/solar/heart-broken-line-duotone')['default']
    ISolarHeartLineDuotone: typeof import('~icons/solar/heart-line-duotone')['default']
    ISolarListHeartMinimalisticLineDuotone: typeof import('~icons/solar/list-heart-minimalistic-line-duotone')['default']
    ISolarMagniferLineDuotone: typeof import('~icons/solar/magnifer-line-duotone')['default']
    ISolarMenuDotsBold: typeof import('~icons/solar/menu-dots-bold')['default']
    ISolarMenuDotsLineDuotone: typeof import('~icons/solar/menu-dots-line-duotone')['default']
    ISolarMicrophoneBoldDuotone: typeof import('~icons/solar/microphone-bold-duotone')['default']
    ISolarMusicNotesBoldDuotone: typeof import('~icons/solar/music-notes-bold-duotone')['default']
    ISolarMutedLineDuotone: typeof import('~icons/solar/muted-line-duotone')['default']
    ISolarPauseBoldDuotone: typeof import('~icons/solar/pause-bold-duotone')['default']
    ISolarPlaaylistMinimalisticBoldDuotone: typeof import('~icons/solar/plaaylist-minimalistic-bold-duotone')['default']
    ISolarPlayBold: typeof import('~icons/solar/play-bold')['default']
    ISolarPlayBoldDuotone: typeof import('~icons/solar/play-bold-duotone')['default']
    ISolarPlayCircleBold: typeof import('~icons/solar/play-circle-bold')['default']
    ISolarPlayCircleLineDuotone: typeof import('~icons/solar/play-circle-line-duotone')['default']
    ISolarPlayLineDuotone: typeof import('~icons/solar/play-line-duotone')['default']
    ISolarPlayStreamLineDuotone: typeof import('~icons/solar/play-stream-line-duotone')['default']
    ISolarQuestionCircleLinear: typeof import('~icons/solar/question-circle-linear')['default']
    ISolarSkipNextBoldDuotone: typeof import('~icons/solar/skip-next-bold-duotone')['default']
    ISolarSkipPreviousBoldDuotone: typeof import('~icons/solar/skip-previous-bold-duotone')['default']
    ISolarUnreadLinear: typeof import('~icons/solar/unread-linear')['default']
    ISolarUserBoldDuotone: typeof import('~icons/solar/user-bold-duotone')['default']
    ISolarUserCircleBoldDuotone: typeof import('~icons/solar/user-circle-bold-duotone')['default']
    ISolarVinylBoldDuotone: typeof import('~icons/solar/vinyl-bold-duotone')['default']
    ISolarVinylLineDuotone: typeof import('~icons/solar/vinyl-line-duotone')['default']
    ISolarVolumeLineDuotone: typeof import('~icons/solar/volume-line-duotone')['default']
    ISolarVolumeLoudLineDuotone: typeof import('~icons/solar/volume-loud-line-duotone')['default']
    ISolarVolumeSmallLineDuotone: typeof import('~icons/solar/volume-small-line-duotone')['default']
  }
}
