/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IFluentDismiss32Regular: typeof import('~icons/fluent/dismiss32-regular')['default']
    ISolarChatDotsLineDuotone: typeof import('~icons/solar/chat-dots-line-duotone')['default']
    ISolarFileRemoveBoldDuotone: typeof import('~icons/solar/file-remove-bold-duotone')['default']
    ISolarGalleryBoldDuotone: typeof import('~icons/solar/gallery-bold-duotone')['default']
    ISolarHamburgerMenuLineDuotone: typeof import('~icons/solar/hamburger-menu-line-duotone')['default']
    ISolarHeartBold: typeof import('~icons/solar/heart-bold')['default']
    ISolarHeartBoldDuotone: typeof import('~icons/solar/heart-bold-duotone')['default']
    ISolarHeartBrokenLineDuotone: typeof import('~icons/solar/heart-broken-line-duotone')['default']
    ISolarHeartLineDuotone: typeof import('~icons/solar/heart-line-duotone')['default']
    ISolarListDownMinimalisticLineDuotone: typeof import('~icons/solar/list-down-minimalistic-line-duotone')['default']
    ISolarListHeartMinimalisticLineDuotone: typeof import('~icons/solar/list-heart-minimalistic-line-duotone')['default']
    ISolarMagniferLineDuotone: typeof import('~icons/solar/magnifer-line-duotone')['default']
    ISolarMenuDotsBold: typeof import('~icons/solar/menu-dots-bold')['default']
    ISolarMenuDotsLineDuotone: typeof import('~icons/solar/menu-dots-line-duotone')['default']
    ISolarMicrophoneBoldDuotone: typeof import('~icons/solar/microphone-bold-duotone')['default']
    ISolarMusicNotesBoldDuotone: typeof import('~icons/solar/music-notes-bold-duotone')['default']
    ISolarMutedLineDuotone: typeof import('~icons/solar/muted-line-duotone')['default']
    ISolarPauseBoldDuotone: typeof import('~icons/solar/pause-bold-duotone')['default']
    ISolarPlaaylistMinimalisticBoldDuotone: typeof import('~icons/solar/plaaylist-minimalistic-bold-duotone')['default']
    ISolarPlayBold: typeof import('~icons/solar/play-bold')['default']
    ISolarPlayBoldDuotone: typeof import('~icons/solar/play-bold-duotone')['default']
    ISolarPlayCircleBold: typeof import('~icons/solar/play-circle-bold')['default']
    ISolarPlayCircleLineDuotone: typeof import('~icons/solar/play-circle-line-duotone')['default']
    ISolarPlayLineDuotone: typeof import('~icons/solar/play-line-duotone')['default']
    ISolarPlaylistMinimalistic3LineDuotone: typeof import('~icons/solar/playlist-minimalistic3-line-duotone')['default']
    ISolarPlayStreamLineDuotone: typeof import('~icons/solar/play-stream-line-duotone')['default']
    ISolarQuestionCircleLinear: typeof import('~icons/solar/question-circle-linear')['default']
    ISolarRadioLineDuotone: typeof import('~icons/solar/radio-line-duotone')['default']
    ISolarRepeatLineDuotone: typeof import('~icons/solar/repeat-line-duotone')['default']
    ISolarRepeatOneLineDuotone: typeof import('~icons/solar/repeat-one-line-duotone')['default']
    ISolarSkipNextBoldDuotone: typeof import('~icons/solar/skip-next-bold-duotone')['default']
    ISolarSkipPreviousBoldDuotone: typeof import('~icons/solar/skip-previous-bold-duotone')['default']
    ISolarUnreadLinear: typeof import('~icons/solar/unread-linear')['default']
    ISolarUserBoldDuotone: typeof import('~icons/solar/user-bold-duotone')['default']
    ISolarUserCircleBoldDuotone: typeof import('~icons/solar/user-circle-bold-duotone')['default']
    ISolarUsersGroupRoundedLineDuotone: typeof import('~icons/solar/users-group-rounded-line-duotone')['default']
    ISolarVinylBoldDuotone: typeof import('~icons/solar/vinyl-bold-duotone')['default']
    ISolarVinylLineDuotone: typeof import('~icons/solar/vinyl-line-duotone')['default']
    ISolarVolumeLoudLineDuotone: typeof import('~icons/solar/volume-loud-line-duotone')['default']
    ISolarVolumeSmallLineDuotone: typeof import('~icons/solar/volume-small-line-duotone')['default']
  }
}

// For TSX support
declare global {
  const IFluentDismiss32Regular: typeof import('~icons/fluent/dismiss32-regular')['default']
  const ISolarChatDotsLineDuotone: typeof import('~icons/solar/chat-dots-line-duotone')['default']
  const ISolarFileRemoveBoldDuotone: typeof import('~icons/solar/file-remove-bold-duotone')['default']
  const ISolarGalleryBoldDuotone: typeof import('~icons/solar/gallery-bold-duotone')['default']
  const ISolarHamburgerMenuLineDuotone: typeof import('~icons/solar/hamburger-menu-line-duotone')['default']
  const ISolarHeartBold: typeof import('~icons/solar/heart-bold')['default']
  const ISolarHeartBoldDuotone: typeof import('~icons/solar/heart-bold-duotone')['default']
  const ISolarHeartBrokenLineDuotone: typeof import('~icons/solar/heart-broken-line-duotone')['default']
  const ISolarHeartLineDuotone: typeof import('~icons/solar/heart-line-duotone')['default']
  const ISolarListDownMinimalisticLineDuotone: typeof import('~icons/solar/list-down-minimalistic-line-duotone')['default']
  const ISolarListHeartMinimalisticLineDuotone: typeof import('~icons/solar/list-heart-minimalistic-line-duotone')['default']
  const ISolarMagniferLineDuotone: typeof import('~icons/solar/magnifer-line-duotone')['default']
  const ISolarMenuDotsBold: typeof import('~icons/solar/menu-dots-bold')['default']
  const ISolarMenuDotsLineDuotone: typeof import('~icons/solar/menu-dots-line-duotone')['default']
  const ISolarMicrophoneBoldDuotone: typeof import('~icons/solar/microphone-bold-duotone')['default']
  const ISolarMusicNotesBoldDuotone: typeof import('~icons/solar/music-notes-bold-duotone')['default']
  const ISolarMutedLineDuotone: typeof import('~icons/solar/muted-line-duotone')['default']
  const ISolarPauseBoldDuotone: typeof import('~icons/solar/pause-bold-duotone')['default']
  const ISolarPlaaylistMinimalisticBoldDuotone: typeof import('~icons/solar/plaaylist-minimalistic-bold-duotone')['default']
  const ISolarPlayBold: typeof import('~icons/solar/play-bold')['default']
  const ISolarPlayBoldDuotone: typeof import('~icons/solar/play-bold-duotone')['default']
  const ISolarPlayCircleBold: typeof import('~icons/solar/play-circle-bold')['default']
  const ISolarPlayCircleLineDuotone: typeof import('~icons/solar/play-circle-line-duotone')['default']
  const ISolarPlayLineDuotone: typeof import('~icons/solar/play-line-duotone')['default']
  const ISolarPlaylistMinimalistic3LineDuotone: typeof import('~icons/solar/playlist-minimalistic3-line-duotone')['default']
  const ISolarPlayStreamLineDuotone: typeof import('~icons/solar/play-stream-line-duotone')['default']
  const ISolarQuestionCircleLinear: typeof import('~icons/solar/question-circle-linear')['default']
  const ISolarRadioLineDuotone: typeof import('~icons/solar/radio-line-duotone')['default']
  const ISolarRepeatLineDuotone: typeof import('~icons/solar/repeat-line-duotone')['default']
  const ISolarRepeatOneLineDuotone: typeof import('~icons/solar/repeat-one-line-duotone')['default']
  const ISolarSkipNextBoldDuotone: typeof import('~icons/solar/skip-next-bold-duotone')['default']
  const ISolarSkipPreviousBoldDuotone: typeof import('~icons/solar/skip-previous-bold-duotone')['default']
  const ISolarUnreadLinear: typeof import('~icons/solar/unread-linear')['default']
  const ISolarUserBoldDuotone: typeof import('~icons/solar/user-bold-duotone')['default']
  const ISolarUserCircleBoldDuotone: typeof import('~icons/solar/user-circle-bold-duotone')['default']
  const ISolarUsersGroupRoundedLineDuotone: typeof import('~icons/solar/users-group-rounded-line-duotone')['default']
  const ISolarVinylBoldDuotone: typeof import('~icons/solar/vinyl-bold-duotone')['default']
  const ISolarVinylLineDuotone: typeof import('~icons/solar/vinyl-line-duotone')['default']
  const ISolarVolumeLoudLineDuotone: typeof import('~icons/solar/volume-loud-line-duotone')['default']
  const ISolarVolumeSmallLineDuotone: typeof import('~icons/solar/volume-small-line-duotone')['default']
}