export { default as AlbumList } from './AlbumList/AlbumList.vue'
export { default as FavoriteSongs } from './FavoriteSongs.vue'
export { default as RecentSongs } from './RecentSongs.vue'
export { default as SonglistsList } from './SonglistsList/SonglistsList.vue'
export { default as UserInfo } from './UserInfo.vue'
